apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: a928v3et8-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/a928v3et8-dotnet-basic-gitops